language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  ## Dossier build
  - mkdir build
  ## Composer
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  ## PHP_CodeSniffer
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
 ## test
  - ls ./vendor/

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PSR1 src/
  - phpcs --standard=PSR2 src/
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose src/
  ## PHP Mess Detector
  # - ./vendor/bin/phpmd src/ text codesize
  ## PHPLOC
  - php phploc.phar --log-csv build/phploc.csv --exclude vendor src/

notifications:
  email:
    - progi1984@gmail.com