language: php
php:
  # 5.3 Composer doesn't support PHP < 5.3.2
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
env:
  global:
  - secure: "TR0pFe8GQjT9cAgXorxAUGGyf7oRamNR2i/3p6sovN/p/PqvzUBHKUzqfxEUEYYOS0sRlgKraM9IGotMbGrGKU8W/az30mjGca6ByKUcqPhIa3QSx48unZK7Ofcu4nosuBBO4zNUPOM9FubgikLXydGyKzO5AS2rHs9YXpTrW7w="

before_script:
  ## Composer
  - composer selfupdate --quiet
  - composer update --prefer-source
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
  ## Atoum
  - mkdir -p build/logs
  - curl -o mageekguy.atoum.phar http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  ## PHPDocumentor
  - mkdir -p build/docs

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs --standard=PSR1 src/
  - ./vendor/bin/phpcs --standard=PSR2 src/
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose src/
  ## PHP Mess Detector
  - phpmd src/ text unusedcode,naming,design
  ## PHPLOC
  - php phploc.phar src/
  ## Atoum
  - php mageekguy.atoum.phar -d tests/ -c .atoum.php
  ## PHPDocumentor
  - vendor/bin/phpdoc.php -d ./src -t ./build/docs

after_script:
 ## Coveralls
 - php vendor/bin/coveralls -v
 ## Scrutinizer
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
 ## PHPDocumentor
 - bash .travis_shell_after_success.sh

notifications:
  email:
    - progi1984@gmail.com
