language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  ## Dossier build
  - mkdir build
  ## Composer
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  ## PHPLOC
  - wget https://phar.phpunit.de/phploc.phar
  ## PHPEnv
  - phpenv rehash

script:
  ## PHP_CodeSniffer
  - vendor/bin/phpcs --standard=PSR1 src/
  - vendor/bin/phpcs --standard=PSR2 src/
  ## PHP Copy/Paste Detector
  - vendor/bin/phpcpd --verbose src/
  ## PHP Mess Detector
  - vendor/bin/phpmd src text codesize
  ## PHPLOC
  - php phploc.phar --log-csv build/phploc.csv --exclude vendor .

notifications:
  email:
    - progi1984@gmail.com