language: php
php:
  # 5.3 Composer doesn't support PHP < 5.3.2
  - 5.3.3
  - 5.4
  - 5.5

before_script:
  ## Composer
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  ## PHP_CodeSniffer
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
  ## Atoum
  - curl -o mageekguy.atoum.phar http://downloads.atoum.org/nightly/mageekguy.atoum.phar

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PSR1 src/
  - phpcs --standard=PSR2 src/
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose src/
  ## PHP Mess Detector
  - phpmd src/ text codesize,unusedcode,naming,design
  ## PHPLOC
  - php phploc.phar src/
  ## Atoum
  - php mageekguy.atoum.phar -d tests/

notifications:
  email:
    - progi1984@gmail.com
